# ============================
# Streamlit - Observatório Curica
# Configurações de Estilo, Servidor e Privacidade
# ============================

[theme]
primaryColor = "#228B22"                 # Verde fosforescente do Diagrama Curica
backgroundColor = "#0E1117"              # Preto carvão (tema escuro)
secondaryBackgroundColor = "#262730"     # Cinza escuro para painéis
textColor = "#FFA07A"                    # Salmão para textos e títulos
font = "sans serif"                      # Fonte legível e moderna

[server]
headless = true                          # Necessário para deploy em servidor
enableCORS = false                       # Segurança para deploy local
port = 8501                              # Porta padrão do Streamlit
runOnSave = true                         # Atualização automática durante desenvolvimento
enableXsrfProtection = true              # Proteção CSRF (ativar em produção)

[client]
toolbarMode = "minimal"                  # Oculta opções de edição e reload
showErrorDetails = true                  # Exibe detalhes em caso de erro

[browser]
gatherUsageStats = false                 # Privacidade: não envia dados para o Streamlit

